### ISSUE TITLE
The FloodSink logging for errors need to be revised - probably dont need stack trace, but need parameters

### ISSUE THREAD

**Issue by erxdkh** [azist/azos#229] opened 2020-01-12 02:24 UTC

**Comment by zhabis** [comment] 2020-01-17 16:39
The problem is with MvcActionException which adds stack traces to message body that is being fixed now

**Comment by zhabis** [comment] 2020-01-17 23:54
Done is MvcActionException

**Comment by erxdkh** [comment] 2020-01-18 02:52
The error log is still full

**Comment by zhabis** [comment] 2020-01-18 23:54
done

**Closed by zhabis** 2020-01-18 23:54 UTC
